### ISSUE TITLE
Small Documentation Suggestion

### ISSUE THREAD

**Issue by Amadeus-** [hayageek/jquery-upload-file#63]
First of all -- big thanks for this project.  It was exactly what I was looking for!!

I just wanted to make a suggestion.   Please consider placing the various localization variables on the main "API & Options" tab at http://hayageek.com/docs/jquery-upload-file.php#doc     The reason I suggest this is because I was actually just looking for a way to customize these strings and just as I was about to come here and ask how it was done, I remembered the localization example, and there it was!

Anyway, having these variables (and their defaults) listed on the "API & Options" page would be useful I think:   dragDropStr, cancelStr, doneStr, multiDragErrorStr, extErrorStr, sizeErrorStr, uploadErrorStr, uploadStr.

**Comment by folksy** [comment]
Hello,

Thank you for contacting Folksy Support. We aim to respond to
queries within one working day but we will get back to you as
soon as possible.

Our standard Support hours are 9am GMT/BST to 5pm GMT/BST
Monday-Friday.

Please note that we offer limited support at the weekends and on
UK Bank Holidays:

https://www.gov.uk/bank-holidays ( https://www.gov.uk/bank-holidays )

While you are waiting, please take a look at our Knowledge Base
for answers to our most frequently asked questions:

http://folksy.uservoice.com/knowledgebase ( http://folksy.uservoice.com/knowledgebase )

If your enquiry relates to a service-critical issue out of office
hours (e.g. your shop has been restricted and you are unable to
process orders), please email us at urgent@folksy.co.uk (
mailto:urgent@folksy.co.uk )

Thank you,

Folksy Support

-----

Email: support@folksy.com ( mailto:support@folksy.com )

Helpdesk (buyer and seller FAQs): http://folksy.uservoice.com/ ( http://folksy.uservoice.com/ )

Blog (including seller tips): http://blog.folksy.com ( http://blog.folksy.com )

Forums (talk to our community): http://talk.folksy.com ( http://talk.folksy.com )

On September 06, 2015 at 10:20 AM hayageek/jquery-upload-file
wrote:

First of all -- big thanks for this project. It was exactly
what I was looking for!!

I just wanted to make a suggestion. Please consider placing the
various localization variables on the main "API & Options" tab at
http://hayageek.com/docs/jquery-upload-file.php#doc ( http://hayageek.com/docs/jquery-upload-file.php#doc ) The
reason I suggest this is because I was actually just looking for
a way to customize these strings and just as I was about to come
here and ask how it was done, I remembered the localization
example, and there it was!

Anyway, having these variables all listed on the "API & Options"
page would be useful I think: dragDropStr, cancelStr, doneStr,
multiDragErrorStr, extErrorStr, sizeErrorStr, uploadErrorStr,
uploadStr.

---

Reply to this email directly or view it on GitHub:

https://github.com/hayageek/jquery-upload-file/issues/63 ( https://github.com/hayageek/jquery-upload-file/issues/63 )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=Folksy&uv_contact_url=folksy.uservoice.com&uv_experience=email )

**Comment by hayageek** [comment]
I will do that.

**Comment by hayageek** [comment]
updated documentation.
