### ISSUE TITLE
onAbort event request

### ISSUE THREAD

**Issue by Amadeus-** [hayageek/jquery-upload-file#66]
I find myself needing an onAbort event (similar to the onCancel) event.    The reason is due to some custom variables I'm using on the form that I'd like to reset (and/or also have the ability to provide information to the user when they abort an upload.)

Anyway, I was looking and it seemed like it might not be too bad to add, so I could probably fork the repo and do a pull request if it's not too hard (again, I'd be modeling after the onCancel event); however, I thought I'd request first in case you might prefer to do it yourself (or, in case you have a good reason why having the event is a bad idea in the first place.)

Thanks!

**Comment by folksy** [comment]
Hello,

Thank you for contacting Folksy Support. We aim to respond to
queries within one working day but we will get back to you as
soon as possible.

Our standard Support hours are 9am GMT/BST to 5pm GMT/BST
Monday-Friday.

Please note that we offer limited support at the weekends and on
UK Bank Holidays:

https://www.gov.uk/bank-holidays ( https://www.gov.uk/bank-holidays )

While you are waiting, please take a look at our Knowledge Base
for answers to our most frequently asked questions:

http://folksy.uservoice.com/knowledgebase ( http://folksy.uservoice.com/knowledgebase )

If your enquiry relates to a service-critical issue out of office
hours (e.g. your shop has been restricted and you are unable to
process orders), please email us at urgent@folksy.co.uk (
mailto:urgent@folksy.co.uk )

Thank you,

Folksy Support

-----

Email: support@folksy.com ( mailto:support@folksy.com )

Helpdesk (buyer and seller FAQs): http://folksy.uservoice.com/ ( http://folksy.uservoice.com/ )

Blog (including seller tips): http://blog.folksy.com ( http://blog.folksy.com )

Forums (talk to our community): http://talk.folksy.com ( http://talk.folksy.com )

On September 12, 2015 at 2:31 AM hayageek/jquery-upload-file
wrote:

I find myself needing an onAbort event (similar to the
onCancel) event. The reason is due to some custom variables
I'm using on the form that I'd like to reset (and/or also have
the ability to provide information to the user when they abort an
upload.)

Anyway, I was looking and it seemed like it might not be too bad
to add, so I could probably fork the repo and do a pull request
if it's not too hard (again, I'd be modeling after the onCancel
event); however, I thought I'd request first in case you might
prefer to do it yourself (or, in case you have a good reason why
having the event is a bad idea in the first place.)

Thanks!

---

Reply to this email directly or view it on GitHub:

https://github.com/hayageek/jquery-upload-file/issues/66 ( https://github.com/hayageek/jquery-upload-file/issues/66 )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=Folksy&uv_contact_url=folksy.uservoice.com&uv_experience=email )

**Comment by hayageek** [comment]
I will do that.

**Comment by hayageek** [comment]
Done. Get the latest code 4.0.6
