### ISSUE TITLE
Add extra HTML elements to fileuploader

### ISSUE THREAD

**Issue by sanaalauddin** [hayageek/jquery-upload-file#67]
Hi. Firstly I'd like to say "Way to go.. This is the best plugin Ive seen so far. Easy to use and diverse in its usage". So Im trying to use this module, adding extra html elements. When I had downloaded the project, this was working a few times I checked. When i tried to edit the code, since then even after inputting the original code, this just doesnt show up. Im not able to select the category. Did I do something wrong? The code looks perfectly fine though. Thanks

**Comment by folksy** [comment]
Hello,

Thank you for contacting Folksy Support. We aim to respond to
queries within one working day but we will get back to you as
soon as possible.

Our standard Support hours are 9am GMT/BST to 5pm GMT/BST
Monday-Friday.

Please note that we offer limited support at the weekends and on
UK Bank Holidays:

https://www.gov.uk/bank-holidays ( https://www.gov.uk/bank-holidays )

While you are waiting, please take a look at our Knowledge Base
for answers to our most frequently asked questions:

http://folksy.uservoice.com/knowledgebase ( http://folksy.uservoice.com/knowledgebase )

If your enquiry relates to a service-critical issue out of office
hours (e.g. your shop has been restricted and you are unable to
process orders), please email us at urgent@folksy.co.uk (
mailto:urgent@folksy.co.uk )

Thank you,

Folksy Support

-----

Email: support@folksy.com ( mailto:support@folksy.com )

Helpdesk (buyer and seller FAQs): http://folksy.uservoice.com/ ( http://folksy.uservoice.com/ )

Blog (including seller tips): http://blog.folksy.com ( http://blog.folksy.com )

Forums (talk to our community): http://talk.folksy.com ( http://talk.folksy.com )

On September 21, 2015 at 5:07 AM hayageek/jquery-upload-file
wrote:

Hi. Firstly I'd like to say "Way to go.. This is the best
plugin Ive seen so far. Easy to use and diverse in its usage". So
Im trying to use this module, adding extra html elements. When I
had downloaded the project, this was working a few times I
checked. When i tried to edit the code, since then even after
inputting the original code, this just doesnt show up. Im not
able to select the category. Did I do something wrong? The code
looks perfectly fine though. Thanks

---

Reply to this email directly or view it on GitHub:

https://github.com/hayageek/jquery-upload-file/issues/67 ( https://github.com/hayageek/jquery-upload-file/issues/67 )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=Folksy&uv_contact_url=folksy.uservoice.com&uv_experience=email )

**Comment by hayageek** [comment]
Looks like js script errors . Can you share me ur code to fix the issue

**Comment by sanaalauddin** [comment]
Can I have your email address? I will email you the test URL. As i have alot of stuff going on in the same page. Thanks

**Comment by hayageek** [comment]
hayageek@gmail.com

**Comment by sanaalauddin** [comment]
I sent you an email.
